### ISSUE TITLE
Permit: create list with permit info

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/token-lists#293]
# Summary

Create a list with permit info.

Should be in the format:

```json
{
  "0x0...": false,
  "0x1...": {
    "type": "eip2612",
    "version": "1"
  },
  "0x2...": {
    "type": "dai-like",
    "version": "2"
  },
  "0x3...": {
    "type": "dai-like"
  }
}
```

* Create a json schema to better define it.
* Create a script to identify a given list of tokens in a network
* Save the results to a `PermitInfo.json` file - one per network
* Create a GH action to update the list whenever the token list is updated
* Expose a lib from CoW Swap for loading the permit info

**Comment by anxolin** [comment]
Great!

I think Fotmat looks great. Only small change i would suggest is to add the network in the file name, instead of having all networks in the same file.

This way, we don't need to load all networks when connected to one.

Just a small comment regarding implementation. If it helps, it might be a good idea to create the utilities in a library inside CoW Swap monorepo. I say this, because its easy to publish to NPM a library from CoW Swap monorepo, and there might be some shared logic and types you can use in both. 

Disregard the past comment if you feel this will add unnecessary work, or would make CoW Swap fat. Just a small suggestion to leverage our ability to easily share code between projects

**Comment by alfetopito** [comment]
Thank you!
Updated the description with your suggestions.
