### ISSUE TITLE
[AddImage] `BaoV2` on `MAINNET`

### ISSUE THREAD

**Issue by fabiaz84** [cowprotocol/token-lists#307]
### Network

MAINNET

### Address

0xce391315b414d4c7555956120461d21808a69f3a

### Image URL

https://github.com/baofinance/bao-app/blob/master/public/images/icons/icon-256.png

**Comment by alfetopito** [comment]
Hi there @fabiaz84 , thank you for your contribution!

The reason it failed is because the link you used is for the github page of the image.
The scripts needs the direct link to the image.
In this case it should https://raw.githubusercontent.com/baofinance/bao-app/master/public/images/icons/icon-256.png

**Comment by fabiaz84** [comment]
> Hi there @fabiaz84 , thank you for your contribution!
> 
> The reason it failed is because the link you used is for the github page of the image. The scripts needs the direct link to the image. In this case it should https://raw.githubusercontent.com/baofinance/bao-app/master/public/images/icons/icon-256.png

Thanks! Will resubmit.
