### ISSUE TITLE
[AddToken] `EURe` on `Sepolia`

### ISSUE THREAD

**Issue by mirceanis** [cowprotocol/token-lists#419]
It would be helpful to be able to cowswap EURe tokens on Sepolia.

0xd58C5Db52B5B3Eb24EE38AF287d2cb0F424172A5 is the token address according to https://monerium.dev/docs/tokens

**Comment by alfetopito** [comment]
Hey there!
Would be happy to add it.
However, it's not tradeable at the moment due to lack of liquidity.

<img width="757" alt="image" src="https://github.com/cowprotocol/token-lists/assets/43217/eb2368c0-ee2c-4e19-a224-0de69652fa8a">

If there is liquidity already available (see [here for the requirements](https://docs.cow.fi/cow-protocol/reference/core/tokens#new-erc-20-tokens)), let me know and I'll poke the guys in charge of the Sepolia solvers.
